/*************************************************************************
	> File Name: EP-029.c
	> Author: 
	> Mail: 
	> Created Time: Sun 16 Jul 2023 10:25:58 PM CST

Problem 29: Distinct powers

Consider all integer combinations of $a^b$ for $2 \le a \le 5$ and $2 \le b \le 5$:

$$\begin{aligned}
& 2^2=4, 2^3=8, 2^4=16, 2^5=32\\
& 3^2=9, 3^3=27, 3^4=81, 3^5=243\\
& 4^2=16, 4^3=64, 4^4=256, 4^5=1024\\
& 5^2=25, 5^3=125, 5^4=625, 5^5=3125\\
\end{aligned}$$

If they are then placed in numerical order, with any repeats removed, we get the following sequence of $15$ distinct terms:

$$4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125$$

How many distinct terms are in the sequence generated by $a^b$ for $2\le a \le 100$ and $2 \le b \le 100$?

 ************************************************************************/

#include<stdio.h>

int main() {
    int num[105][2] = {1};
    for (int i = 2; i <= 10; i++) {
        int n = i, k = 1;
        while (n <= 100) {
            num[n][0] = i;
            num[n][1] = k;
            n *= i;
            k += 1;
        }
    }
    for (int i = 2; i <= 100; i++) {
        if (num[i][0] != 1) continue;
        num[i][0] = i;
    }
    int arr[10005][2] = {0};
    for (int i = 2; i <= 100; i++) {
        int k = i, flag = 1;
        for (int j = 2; j <= 100; j++) {
            for (int u = 1; u <= 10000; u++) {
                if (arr[u][0] != num[k][0] || arr[u][1] != j * num[k][1]) continue;
                flag = 0;
                break;
            }
            if (!flag) continue;
            arr[++arr[0][0]][0] = num[k][0];
            arr[arr[0][0]][1] = j * num[k][1];
        }
    }
    printf("%d\n", arr[0][0]);
    return 0;
}
