/*************************************************************************
	> File Name: EP-012.c
	> Author: 
	> Mail: 
	> Created Time: Sun 16 Jul 2023 11:00:51 PM CST

Problem 12: Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers. So the $7$th triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten terms would be:

$$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \ldots $$

Let us list the factors of the first seven triangle numbers:

$$\begin{aligned}
\bf{1:}\ & 1\\
\bf{3:}\ & 1,3\\
\bf{6:}\ & 1,2,3,6 \\
\bf{10:}\ & 1,2,5,10 \\
\bf{15:}\ & 1,3,5,15 \\
\bf{21:}\ & 1,3,7,21 \\
\bf{28:}\ & 1,2,4,7,14,28 \\
\end{aligned}$$

We can see that $28$ is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

 ************************************************************************/

#include<stdio.h>
#define MAX_N 100

int prime[MAX_N + 5] = {0};
int f[MAX_N + 5] = {0};
void init() {
    for (int i = 2; i <= MAX_N; i++) {
        if (!prime[i]) {
            prime[++prime[0]] = i;
            f[i] = 2;
        }
        for (int j = 1; j <= prime[0]; j++) {
            if (prime[j] * i > MAX_N) break;
            prime[prime[j] * i] = 1;
            if (i % prime[j] == 0) {
                
                break;
            } else {

            }
        }
    }
    return ;
}

int main() {
    init();
    int n = 0;
    while (1) {
        n++;
        int val = (n & 1) ? f[n] * f[(n + 1) >> 1] : f[n >> 1] * f[n + 1];
        if (val <= 500) continue;
        printf("%d\n", val);
        break;
    }
    return 0;
}
