/*************************************************************************
	> File Name: EP-002.c
	> Author: 
	> Mail: 
	> Created Time: Mon 10 Jul 2023 09:04:23 PM CST

Problem 2 :

Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:

$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \ldots$$

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 ************************************************************************/

#include<stdio.h>
#include <stdlib.h>
#define MAX_N 4000000

int main() {
    int a = 2, b = 1;
    int sum = 2;
    while (a + b < MAX_N) {
        a = a + b;
        b = a - b;
        if (a & 1) continue;
        sum += a;
    }
    printf("%d\n", sum);
    return 0;
}
